### ISSUE TITLE
[1.18] Crash when joining a server.

### ISSUE THREAD

**Issue by Cixon** [Ladysnake/Illuminations-for-Forge#8]
**Log (686):**

[latest.log](https://github.com/Ladysnake/Illuminations-for-Forge/files/9482862/latest.log)

**Crash:**

[crash-2022-09-03_10.59.09-client.txt](https://github.com/Ladysnake/Illuminations-for-Forge/files/9482863/crash-2022-09-03_10.59.09-client.txt)

**Comment by Cixon** [comment]
using [v0.0.4]

**Comment by AbsolemJackdaw** [comment]
there is no 1.18 for forge
illuminations for forge has been discontinued since 1.15 due to lack of time and the massive content gap
